layout_spectrum: 0.6866727
typography_spectrum: 0.125339
color:
  saturation: 0.8099168
  lightness: 0.312344
  brandStrength: 0.6692932
  rhythmicContrast: 0.8646036
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Zurich
